##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://catherinefrank101.github.io
# path to location on the domain if necessary
baseurl: /punk-war-on-the-boulevard
# location of code, the full url to your github repository
source-code: https://github.com/catherinefrank101/punk-war-on-the-boulevard

##########
# SITE SETTINGS
#
title: Punk War on the Boulevard
tagline: A Digital Collection Built with CollectionBuilder
description: "A digital collection of punk flyers and zines from archival collections."
keywords: punk; archives; zines; flyers; digital collection
author: Catherine Frank

##########
# COLLECTION SETTINGS
#
# Name of CSV file in the _data folder (WITHOUT .csv)
metadata: full_metadata

##########
# ORGANIZATION SETTINGS
#
organization-name: "Center for Digital Inquiry and Learning (CDIL)"
organization-link: https://cdil.lib.uidaho.edu/

organization-logo-banner: https://www.lib.uidaho.edu/collectionbuilder/cdil-black.png
organization-logo-nav: https://www.lib.uidaho.edu/collectionbuilder/cdil-white.png

##########
# BUILD SETTINGS
#
lib-assets: /assets/lib

exclude:
  - docs/
  - Rakefile
  - rakelib/
  - README.md
  - LICENSE
  - CITATION.cff
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - SECURITY.md

sass:
  style: compressed
